// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneNumberArea.API.Data;

#nullable disable

namespace PhoneNumberArea.API.Migrations
{
    [DbContext(typeof(PhoneNumberAreaDbContext))]
    partial class PhoneNumberAreaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PhoneNumberArea.API.Data.AreaCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("AreaCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 918,
                            StateId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = 405,
                            StateId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = 580,
                            StateId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = 281,
                            StateId = 2
                        },
                        new
                        {
                            Id = 5,
                            Code = 346,
                            StateId = 2
                        },
                        new
                        {
                            Id = 6,
                            Code = 713,
                            StateId = 2
                        },
                        new
                        {
                            Id = 7,
                            Code = 832,
                            StateId = 2
                        },
                        new
                        {
                            Id = 8,
                            Code = 406,
                            StateId = 3
                        });
                });

            modelBuilder.Entity("PhoneNumberArea.API.Data.County", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AreaCodeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaCodeId");

                    b.ToTable("Counties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaCodeId = 1,
                            Name = "Muskogee"
                        },
                        new
                        {
                            Id = 2,
                            AreaCodeId = 2,
                            Name = "Blaine"
                        },
                        new
                        {
                            Id = 3,
                            AreaCodeId = 3,
                            Name = "Alfalfa"
                        },
                        new
                        {
                            Id = 4,
                            AreaCodeId = 4,
                            Name = "Harris"
                        },
                        new
                        {
                            Id = 5,
                            AreaCodeId = 5,
                            Name = "Pasadena"
                        },
                        new
                        {
                            Id = 6,
                            AreaCodeId = 6,
                            Name = "Galveston"
                        },
                        new
                        {
                            Id = 7,
                            AreaCodeId = 7,
                            Name = "Brazoria"
                        },
                        new
                        {
                            Id = 8,
                            AreaCodeId = 8,
                            Name = "Big Sky"
                        },
                        new
                        {
                            Id = 9,
                            AreaCodeId = 8,
                            Name = "Glacier"
                        });
                });

            modelBuilder.Entity("PhoneNumberArea.API.Data.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "OK",
                            Name = "Oklahoma"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "TX",
                            Name = "Texas"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "MT",
                            Name = "Montana"
                        });
                });

            modelBuilder.Entity("PhoneNumberArea.API.Data.AreaCode", b =>
                {
                    b.HasOne("PhoneNumberArea.API.Data.State", "State")
                        .WithMany("AreaCodes")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("PhoneNumberArea.API.Data.County", b =>
                {
                    b.HasOne("PhoneNumberArea.API.Data.AreaCode", "AreaCode")
                        .WithMany("Counties")
                        .HasForeignKey("AreaCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaCode");
                });

            modelBuilder.Entity("PhoneNumberArea.API.Data.AreaCode", b =>
                {
                    b.Navigation("Counties");
                });

            modelBuilder.Entity("PhoneNumberArea.API.Data.State", b =>
                {
                    b.Navigation("AreaCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
